### ISSUE TITLE
bindings: python: external module expects return type classes to be in globals()

### ISSUE THREAD

**Issue by vfazio** [brgl/libgpiod#101]
When calling functions like `gpiod.chip.Chip.get_info`, calls are forwarded to the external module to create an object and return it.

Right now, we include `gpiod.chip_info.ChipInfo` as an import in `gpiod.chip`. The module itself does not consume or create instances of `ChipInfo` so it's only purpose is "superficial" and is used for type checking.

However, if i put the import behind a `TYPE_CHECKING` guard so it's only available when actually type checking a la:

```python
if TYPE_CHECKING:
    from .chip_info import ChipInfo
```

We get unit test errors:

```
vfazio4 /mnt/development/libgpiod/bindings/python :( # LD_LIBRARY_PATH=/mnt/development/libgpiod/lib/.libs/:/mnt/development/libgpiod/tests/gpiosim/.libs/ ./venv/bin/python -m unittest tests.tests_info_event.WatchingInfoEventWorks.test_watch_line_info_returns_line_info
E
======================================================================
ERROR: test_watch_line_info_returns_line_info (tests.tests_info_event.WatchingInfoEventWorks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/development/libgpiod/bindings/python/tests/tests_info_event.py", line 71, in test_watch_line_info_returns_line_info
    info = self.chip.watch_line_info(7)
  File "/mnt/development/libgpiod/bindings/python/gpiod/chip.py", line 191, in watch_line_info
    return self._get_line_info(line, watch=True)
  File "/mnt/development/libgpiod/bindings/python/gpiod/chip.py", line 164, in _get_line_info
    return self._chip.get_line_info(self.line_offset_from_id(line), watch)
  File "/mnt/development/libgpiod/bindings/python/gpiod/chip.py", line 156, in line_offset_from_id
    if offset >= self.get_info().num_lines:
  File "/mnt/development/libgpiod/bindings/python/gpiod/chip.py", line 118, in get_info
    self._info = self._chip.get_info()
SystemError: <method 'get_info' of 'gpiod._ext.Chip' objects> returned NULL without setting an error

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

This seems to be because the external module looks for the classes within `globals()`:

```c
type = Py_gpiod_GetGlobalType("ChipInfo");
```

So we have an implicit dependency on `gpiod.chip` importing `gpiod.chip_info.ChipInfo` for this (or any similar) lookup to work.

We may be able to avoid this by explicitly importing the class we need:

```diff
diff --git a/bindings/python/gpiod/ext/chip.c b/bindings/python/gpiod/ext/chip.c
index e8eaad8..8826d7e 100644
--- a/bindings/python/gpiod/ext/chip.c
+++ b/bindings/python/gpiod/ext/chip.c
@@ -73,22 +73,25 @@ static PyObject *chip_close(chip_object *self, PyObject *Py_UNUSED(ignored))
 static PyObject *chip_get_info(chip_object *self, PyObject *Py_UNUSED(ignored))
 {
        struct gpiod_chip_info *info;
-       PyObject *type, *ret;
+       PyObject *type, *ret, *module = NULL;
 
-       type = Py_gpiod_GetGlobalType("ChipInfo");
-       if (!type)
-               return NULL;
+       module = PyImport_ImportModule("gpiod.chip_info");
+       if (!module)
+               return PyErr_SetFromErrno(PyExc_ImportError);
 
        info = gpiod_chip_get_info(self->chip);
-       if (!info)
-               return PyErr_SetFromErrno(PyExc_OSError);
-
-        ret = PyObject_CallFunction(type, "ssI",
-                                    gpiod_chip_info_get_name(info),
-                                    gpiod_chip_info_get_label(info),
-                                    gpiod_chip_info_get_num_lines(info));
-        gpiod_chip_info_free(info);
-        return ret;
+       if (!info) {
+               ret = PyErr_SetFromErrno(PyExc_OSError);
+       }
+       else {
+               ret = PyObject_CallMethod(module, "ChipInfo", "ssI",
+                                               gpiod_chip_info_get_name(info),
+                                               gpiod_chip_info_get_label(info),
+                                               gpiod_chip_info_get_num_lines(info));
+               gpiod_chip_info_free(info);
+       }
+       Py_DECREF(module);
+       return ret;
 }
```

```
vfazio4 /mnt/development/libgpiod/bindings/python # LD_LIBRARY_PATH=/mnt/development/libgpiod/lib/.libs/:/mnt/development/libgpiod/tests/gpiosim/.libs/ ./venv/bin/python -m unittest tests.tests_info_event.WatchingInfoEventWorks.test_watch_line_info_returns_line_info
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK

```

I don't have much experience with the Python C API so this was just a best guess at getting something working and may not be fully correct from an API perspective (like making sure ref counts are correct).

It's a bit of a weird scenario where gpiod imports _ext but _ext needs gpiod. I don't know if there's a better method to cache the module reference instead of looking it up every function call, but I have a feeling the circular dependency situation may cause problems if not done correctly, which lazy lookups/imports may avoid.

**Comment by brgl** [comment]
That's a good catch! Are there more instances like that? The patch looks correct to me wrt reference counting. Do you want to send it to the list?

**Comment by vfazio** [comment]
> That's a good catch! Are there more instances like that? The patch looks correct to me wrt reference counting. Do you want to send it to the list?

@brgl there are definitely other places. If you want, I can go through and document them in this issue.

This is one of the nice things about using linters. Running https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch checks helped me identify this.

I thought about including this in the series I plan to submit soon, but it's already 22 patches long and getting rather unwieldy. I will likely just spin up another set of patches for these fixes. After they land, another patch can be made to move the imports behind the `TYPE_CHECKING` guard.

**Comment by vfazio** [comment]
The following functions are affected:

```
chip_get_info -> ChipInfo (Chip.get_info)
make_line_info -> LineInfo (Chip.get_line_info, Chip.read_info_event)
chip_read_info_event -> InfoEvent (Chip.read_info_event)
request_get_values -> Value (Request.get_values)
request_read_edge_events -> EdgeEvent (Request.read_edge_events)
```

**Comment by brgl** [comment]
Thanks. So are you planning on getting to it eventually or should I start fixing it? Also: the "returned NULL without setting an error" thing is an issue too, we should definitely set an error on every failure in the ext module.

**Comment by vfazio** [comment]
@brgl I will probably get to it eventually but may not be as quick as you. 

I did not do an analysis of all places that returned NULL that didn't set an error. It's actually not clear to me what standard Python C API functions set an error or if it's up to the caller to do that by querying PyErr_Occurred?. I see many instances of CPython returning Null without an explicit PyErr_SetString(). Finding and resolving those also seems like it may be a bit more time intensive.

**Comment by brgl** [comment]
In that case I'll spend some time cleaning it up. Should I wait for your big series with it? Will it even touch any of the C code?

**Comment by vfazio** [comment]
I'm purposefully not touching any of the C code. I'm trying to actually not change any functionality at all with this series. All code coverage and functional tests should be equivalent.

The only thing that may be affected is if you changed any of the return types from the exported module functions since i've added typing for those, but I don't think that's necessary or your intention for these fixes.

**Comment by vfazio** [comment]
Apparently `PyImport_ImportModule` will set `ModuleNotFoundError`

```c
	module = PyImport_ImportModule("gpiod.chip_inf");
	if (PyErr_Occurred())
		PyErr_Print();
	if (!module)
		return NULL;
```

```
ModuleNotFoundError: No module named 'gpiod.chip_inf
```

`PyObject_CallMethod` will also set an `AttributeError` if it hits an issue:

```c
	} else {
		ret = PyObject_CallMethod(module, "ChipInf", "ssI",
					  gpiod_chip_info_get_name(info),
					  gpiod_chip_info_get_label(info),
					  gpiod_chip_info_get_num_lines(info));
	 	gpiod_chip_info_free(info);
	}
```
```
AttributeError: module 'gpiod.chip_info' has no attribute 'ChipInf'
```

**Comment by vfazio** [comment]
I don't know how you feel about `goto`, but here's a possible implementation:

```c
static PyObject *chip_get_info(chip_object *self, PyObject *Py_UNUSED(ignored))
{
	struct gpiod_chip_info *info;
	PyObject *module = NULL, *ret = NULL, *attr = NULL;

	module = PyImport_ImportModule("gpiod.chip_info");
	if (!module)
		return NULL;

	info = gpiod_chip_get_info(self->chip);
	if (!info) {
		ret = PyErr_SetFromErrno(PyExc_OSError);
		goto out;
	}
	attr = PyObject_GetAttrString(module, "ChipInfo");
	if (!attr)
		goto free_info;

	ret = PyObject_CallFunction(attr, "ssI",
				    gpiod_chip_info_get_name(info),
				    gpiod_chip_info_get_label(info),
				    gpiod_chip_info_get_num_lines(info));
free_info:
	gpiod_chip_info_free(info);
out:	
	Py_DECREF(module);
	return ret;
}
```

I don't know if there's a benefit of calling `PyObject_GetAttrString + PyObject_CallFunction` vs just calling `PyObject_CallMethod`

**Comment by brgl** [comment]
> I don't know how you feel about `goto`, but here's a possible implementation:
> 

I'm fine if used in correct context.

> 
> I don't know if there's a benefit of calling `PyObject_GetAttrString + PyObject_CallFunction` vs just calling `PyObject_CallMethod`

I think `PyObject_CallMethod` will end up doing the former internally anyway.

**Comment by vfazio** [comment]
indeed

```c
PyObject *
PyObject_CallMethod(PyObject *obj, const char *name, const char *format, ...)
{
    PyThreadState *tstate = _PyThreadState_GET();

    if (obj == NULL || name == NULL) {
        return null_error(tstate);
    }

    PyObject *callable = PyObject_GetAttrString(obj, name);
    if (callable == NULL) {
        return NULL;
    }

    va_list va;
    va_start(va, format);
    PyObject *retval = callmethod(tstate, callable, format, va);
    va_end(va);

    Py_DECREF(callable);
    return retval;
}

static PyObject*
callmethod(PyThreadState *tstate, PyObject* callable, const char *format, va_list va)
{
    assert(callable != NULL);
    if (!PyCallable_Check(callable)) {
        _PyErr_Format(tstate, PyExc_TypeError,
                      "attribute of type '%.200s' is not callable",
                      Py_TYPE(callable)->tp_name);
        return NULL;
    }

    return _PyObject_CallFunctionVa(tstate, callable, format, va);
}
```

vs

```c
PyObject *
PyObject_CallFunction(PyObject *callable, const char *format, ...)
{
    va_list va;
    PyObject *result;
    PyThreadState *tstate = _PyThreadState_GET();

    va_start(va, format);
    result = _PyObject_CallFunctionVa(tstate, callable, format, va);
    va_end(va);

    return result;
}
```
It does at least remember to decrement the callable ref when done, unlike my example.

**Comment by vfazio** [comment]
I'm not sure how busy you are or what your plans are for the next version of the python bindings is with 2.2.x-rc2 announced. I can try to submit a patch tomorrow or Friday that builds and passes tests.

**Comment by brgl** [comment]
@vfazio python bindings are largely separate on pypi so the v2.2 release doesn't concern them much.

**Comment by vfazio** [comment]
rough draft


```diff
From 4c9bff3b19eb7a4443ef227dbf4d3ef82fa42e03 Mon Sep 17 00:00:00 2001
From: Vincent Fazio <vfazio@xes-inc.com>
Date: Thu, 3 Oct 2024 15:21:08 -0500
Subject: [PATCH] bindings: python: explicitly import gpiod classes within
 external module

Previously, the external module implicitly relied on gpiod classes being
present with `globals()` to construct return values back to gpiod.

However, this required callers to the external module methods to have
imported the attributes to populate `globals()` for this to function
correctly. This contract is very opaque and prone to causing issues if
imports within gpiod modules get reworked.

Now, the external module explicitly imports class attributes from gpiod.

There should be no concern about circular imports as the external module
should be completely imported by the time callers call into it.

Signed-off-by: Vincent Fazio <vfazio@xes-inc.com>
---
 bindings/python/gpiod/ext/chip.c     | 35 +++++++++++++++++-----------
 bindings/python/gpiod/ext/common.c   | 14 +++++++----
 bindings/python/gpiod/ext/internal.h |  3 ++-
 bindings/python/gpiod/ext/request.c  | 29 +++++++++++++++++------
 4 files changed, 55 insertions(+), 26 deletions(-)

diff --git a/bindings/python/gpiod/ext/chip.c b/bindings/python/gpiod/ext/chip.c
index e8eaad8..b5c3740 100644
--- a/bindings/python/gpiod/ext/chip.c
+++ b/bindings/python/gpiod/ext/chip.c
@@ -75,31 +75,34 @@ static PyObject *chip_get_info(chip_object *self, PyObject *Py_UNUSED(ignored))
        struct gpiod_chip_info *info;
        PyObject *type, *ret;
 
-       type = Py_gpiod_GetGlobalType("ChipInfo");
+       type = Py_gpiod_GetModuleAttrString("gpiod.chip_info", "ChipInfo");
        if (!type)
                return NULL;
 
        info = gpiod_chip_get_info(self->chip);
-       if (!info)
+       if (!info) {
+               Py_DECREF(type);
                return PyErr_SetFromErrno(PyExc_OSError);
+       }
 
-        ret = PyObject_CallFunction(type, "ssI",
-                                    gpiod_chip_info_get_name(info),
-                                    gpiod_chip_info_get_label(info),
-                                    gpiod_chip_info_get_num_lines(info));
-        gpiod_chip_info_free(info);
-        return ret;
+       ret = PyObject_CallFunction(type, "ssI",
+                                   gpiod_chip_info_get_name(info),
+                                   gpiod_chip_info_get_label(info),
+                                   gpiod_chip_info_get_num_lines(info));
+       gpiod_chip_info_free(info);
+       Py_DECREF(type);
+       return ret;
 }
 
 static PyObject *make_line_info(struct gpiod_line_info *info)
 {
-       PyObject *type;
+       PyObject *type, *ret;
 
-       type = Py_gpiod_GetGlobalType("LineInfo");
+       type = Py_gpiod_GetModuleAttrString("gpiod.line_info", "LineInfo");
        if (!type)
                return NULL;
 
-       return PyObject_CallFunction(type, "IsOsiOiiiiOk",
+       ret = PyObject_CallFunction(type, "IsOsiOiiiiOk",
                                gpiod_line_info_get_offset(info),
                                gpiod_line_info_get_name(info),
                                gpiod_line_info_is_used(info) ?
@@ -115,6 +118,8 @@ static PyObject *make_line_info(struct gpiod_line_info *info)
                                gpiod_line_info_is_debounced(info) ?
                                                        Py_True : Py_False,
                                gpiod_line_info_get_debounce_period_us(info));
+       Py_DECREF(type);
+       return ret;
 }
 
 static PyObject *chip_get_line_info(chip_object *self, PyObject *args)
@@ -168,21 +173,24 @@ chip_read_info_event(chip_object *self, PyObject *Py_UNUSED(ignored))
        struct gpiod_info_event *event;
        struct gpiod_line_info *info;
 
-       type = Py_gpiod_GetGlobalType("InfoEvent");
+       type = Py_gpiod_GetModuleAttrString("gpiod.info_event", "InfoEvent");
        if (!type)
                return NULL;
 
        Py_BEGIN_ALLOW_THREADS;
        event = gpiod_chip_read_info_event(self->chip);
        Py_END_ALLOW_THREADS;
-       if (!event)
+       if (!event) {
+               Py_DECREF(type);
                return Py_gpiod_SetErrFromErrno();
+       }
 
        info = gpiod_info_event_get_line_info(event);
 
        info_obj = make_line_info(info);
        if (!info_obj) {
                gpiod_info_event_free(event);
+               Py_DECREF(type);
                return NULL;
        }
 
@@ -192,6 +200,7 @@ chip_read_info_event(chip_object *self, PyObject *Py_UNUSED(ignored))
                                info_obj);
        Py_DECREF(info_obj);
        gpiod_info_event_free(event);
+       Py_DECREF(type);
        return event_obj;
 }
 
diff --git a/bindings/python/gpiod/ext/common.c b/bindings/python/gpiod/ext/common.c
index 07fca8c..62201b6 100644
--- a/bindings/python/gpiod/ext/common.c
+++ b/bindings/python/gpiod/ext/common.c
@@ -64,15 +64,19 @@ PyObject *Py_gpiod_SetErrFromErrno(void)
        return PyErr_SetFromErrno(exc);
 }
 
-PyObject *Py_gpiod_GetGlobalType(const char *type_name)
+PyObject *Py_gpiod_GetModuleAttrString(const char *modname,
+                                      const char *attrname)
 {
-       PyObject *globals;
+       PyObject *module, *attribute;
 
-       globals = PyEval_GetGlobals();
-       if (!globals)
+       module = PyImport_ImportModule(modname);
+       if (!module)
                return NULL;
 
-       return PyDict_GetItemString(globals, type_name);
+       attribute = PyObject_GetAttrString(module, attrname);
+       Py_DECREF(module);
+
+       return attribute;
 }
 
 unsigned int Py_gpiod_PyLongAsUnsignedInt(PyObject *pylong)
diff --git a/bindings/python/gpiod/ext/internal.h b/bindings/python/gpiod/ext/internal.h
index 7d223c0..15aedfb 100644
--- a/bindings/python/gpiod/ext/internal.h
+++ b/bindings/python/gpiod/ext/internal.h
@@ -8,7 +8,8 @@
 #include <Python.h>
 
 PyObject *Py_gpiod_SetErrFromErrno(void);
-PyObject *Py_gpiod_GetGlobalType(const char *type_name);
+PyObject *Py_gpiod_GetModuleAttrString(const char *modname,
+                                      const char *attrname);
 unsigned int Py_gpiod_PyLongAsUnsignedInt(PyObject *pylong);
 void Py_gpiod_dealloc(PyObject *self);
 PyObject *Py_gpiod_MakeRequestObject(struct gpiod_line_request *request,
diff --git a/bindings/python/gpiod/ext/request.c b/bindings/python/gpiod/ext/request.c
index 5db69fe..fb84029 100644
--- a/bindings/python/gpiod/ext/request.c
+++ b/bindings/python/gpiod/ext/request.c
@@ -149,13 +149,15 @@ static PyObject *request_get_values(request_object *self, PyObject *args)
        if (num_offsets < 0)
                return NULL;
 
-       type = Py_gpiod_GetGlobalType("Value");
+       type = Py_gpiod_GetModuleAttrString("gpiod.line", "Value");
        if (!type)
                return NULL;
 
        iter = PyObject_GetIter(offsets);
-       if (!iter)
+       if (!iter) {
+               Py_DECREF(type);
                return NULL;
+       }
 
        clear_buffers(self);
 
@@ -170,6 +172,7 @@ static PyObject *request_get_values(request_object *self, PyObject *args)
                Py_DECREF(next);
                if (PyErr_Occurred()) {
                        Py_DECREF(iter);
+                       Py_DECREF(type);
                        return NULL;
                }
        }
@@ -180,17 +183,22 @@ static PyObject *request_get_values(request_object *self, PyObject *args)
                                                   self->offsets,
                                                   self->values);
        Py_END_ALLOW_THREADS;
-       if (ret)
+       if (ret) {
+               Py_DECREF(type);
                return Py_gpiod_SetErrFromErrno();
+       }
 
        for (pos = 0; pos < num_offsets; pos++) {
                val = PyObject_CallFunction(type, "i", self->values[pos]);
-               if (!val)
+               if (!val) {
+                       Py_DECREF(type);
                        return NULL;
+               }
 
                ret = PyList_SetItem(values, pos, val);
                if (ret) {
                        Py_DECREF(val);
+                       Py_DECREF(type);
                        return NULL;
                }
        }
@@ -279,7 +287,7 @@ static PyObject *request_read_edge_events(request_object *self, PyObject *args)
                max_events = 64;
        }
 
-       type = Py_gpiod_GetGlobalType("EdgeEvent");
+       type = Py_gpiod_GetModuleAttrString("gpiod.edge_event", "EdgeEvent");
        if (!type)
                return NULL;
 
@@ -287,19 +295,24 @@ static PyObject *request_read_edge_events(request_object *self, PyObject *args)
        ret = gpiod_line_request_read_edge_events(self->request,
                                                 self->buffer, max_events);
        Py_END_ALLOW_THREADS;
-       if (ret < 0)
+       if (ret < 0) {
+               Py_DECREF(type);
                return Py_gpiod_SetErrFromErrno();
+       }
 
        num_events = ret;
 
        events = PyList_New(num_events);
-       if (!events)
+       if (!events) {
+               Py_DECREF(type);
                return NULL;
+       }
 
        for (i = 0; i < num_events; i++) {
                event = gpiod_edge_event_buffer_get_event(self->buffer, i);
                if (!event) {
                        Py_DECREF(events);
+                       Py_DECREF(type);
                        return NULL;
                }
 
@@ -311,6 +324,7 @@ static PyObject *request_read_edge_events(request_object *self, PyObject *args)
                                gpiod_edge_event_get_line_seqno(event));
                if (!event_obj) {
                        Py_DECREF(events);
+                       Py_DECREF(type);
                        return NULL;
                }
 
@@ -318,6 +332,7 @@ static PyObject *request_read_edge_events(request_object *self, PyObject *args)
                if (ret) {
                        Py_DECREF(event_obj);
                        Py_DECREF(events);
+                       Py_DECREF(type);
                        return NULL;
                }
        }
-- 
2.34.1
```

**Comment by brgl** [comment]
Looks awesome, does this fix all the instances you listed [here](https://github.com/brgl/libgpiod/issues/101#issuecomment-2379076012)?

**Comment by vfazio** [comment]
https://lore.kernel.org/linux-gpio/20241004171438.3066379-1-vfazio@xes-inc.com/T/#u

**Comment by vfazio** [comment]
submitted v2 to address comments https://lore.kernel.org/linux-gpio/20241008175139.1198980-1-vfazio@xes-inc.com/T/#u
